/**
 * Mock Data Factories - Create mock objects for testing
 */

export const createMockUser = (overrides = {}) => ({
  id: 1,
  username: 'testuser',
  isAdmin: false,
  visits: 0,
  routes_started: 0,
  routes_completed: 0,
  questions_answered: 0,
  ...overrides
});

export const createMockBusinessUser = (overrides = {}) => ({
  id: 1,
  username: 'testbusiness',
  status: 'approved',
  storeId: 1,
  goal: 10,
  ...overrides
});

export const createMockStore = (overrides = {}) => ({
  id: 1,
  name: 'Test Store',
  latitude: 40.7128,
  longitude: -74.0060,
  address: '123 Test St, New York, NY 10001',
  amenity: 'cafe',
  cuisine: 'coffee',
  website: 'https://teststore.com',
  phone: '+1-555-0123',
  isVerified: false,
  ...overrides
});

export const createMockRoute = (overrides = {}) => ({
  id: 1,
  name: 'Test Route',
  routeType: 'coffee',
  isAutoGenerated: false,
  stores: [createMockStore()],
  storeCount: 1,
  ...overrides
});

export const createMockAchievement = (overrides = {}) => ({
  id: 1,
  name: 'First Visit',
  description: 'Visit your first store',
  type: 'visits',
  condition: 1,
  unlocked: false,
  unlockedAt: null,
  ...overrides
});

export const createMockVisit = (overrides = {}) => ({
  id: 1,
  userId: 1,
  storeId: 1,
  visitDate: new Date().toISOString(),
  store: createMockStore(),
  ...overrides
});

export const createMockQuestion = (overrides = {}) => ({
  fieldName: 'price_range',
  questionText: 'How would you rate the prices?',
  type: 'select',
  options: [
    { value: 'cheap', label: 'Budget-friendly' },
    { value: 'moderate', label: 'Moderate' },
    { value: 'expensive', label: 'Expensive' }
  ],
  ...overrides
});

export const createMockTokens = () => ({
  accessToken: 'mock-access-token-12345',
  refreshToken: 'mock-refresh-token-67890'
});

export const createMockPunchcard = (overrides = {}) => ({
  id: 1,
  customer_username: 'testuser',
  business_username: 'testbusiness',
  punches: 5,
  ...overrides
});

export const createMockRouteStart = (overrides = {}) => ({
  id: 1,
  userId: 1,
  routeId: 1,
  status: 'active',
  progress: 0,
  route: createMockRoute(),
  ...overrides
});

export const createMockSavedStore = (overrides = {}) => ({
  id: 1,
  userId: 1,
  storeId: 1,
  store: createMockStore(),
  ...overrides
});
