/**
 * Mock data fixtures for tests
 */

// Valid user credentials
const validUserCredentials = {
  username: 'testuser',
  password: 'password123'
};

// Valid business credentials
const validBusinessCredentials = {
  username: 'testbusiness',
  password: 'business123'
};

// Valid admin credentials
const validAdminCredentials = {
  username: 'admin',
  password: 'admin123'
};

// Sample stores for testing
const sampleStores = [
  {
    id: 1,
    name: 'Coffee Shop',
    latitude: 40.7128,
    longitude: -74.0060,
    address: '123 Main St',
    amenity: 'cafe',
    cuisine: 'coffee',
    status: 'active'
  },
  {
    id: 2,
    name: 'Pizza Place',
    latitude: 40.7130,
    longitude: -74.0065,
    address: '456 Oak Ave',
    amenity: 'restaurant',
    cuisine: 'pizza',
    status: 'active'
  },
  {
    id: 3,
    name: 'Pending Store',
    latitude: 40.7135,
    longitude: -74.0070,
    address: '789 Elm St',
    amenity: 'restaurant',
    cuisine: 'italian',
    status: 'pending'
  }
];

// Sample businesses for testing
const sampleBusinesses = [
  {
    id: 1,
    username: 'approvedbiz',
    status: 'approved',
    goal: 10,
    storeId: 1
  },
  {
    id: 2,
    username: 'pendingbiz',
    status: 'pending',
    goal: 10,
    storeId: null
  }
];

// Sample routes for testing
const sampleRoutes = [
  {
    id: 1,
    name: 'Downtown Walk',
    routeType: 'walking',
    isAutoGenerated: false
  },
  {
    id: 2,
    name: 'Auto Route 1',
    routeType: 'driving',
    isAutoGenerated: true
  }
];

// Sample achievements for testing
const sampleAchievements = [
  {
    id: 1,
    name: 'First Steps',
    description: 'Visit your first store',
    type: 'visits',
    condition: 1
  },
  {
    id: 2,
    name: 'Regular',
    description: 'Visit 10 stores',
    type: 'visits',
    condition: 10
  },
  {
    id: 3,
    name: 'Route Starter',
    description: 'Start your first route',
    type: 'routes_started',
    condition: 1
  }
];

// Nearby search parameters
const nearbySearchParams = {
  latitude: 40.7128,
  longitude: -74.0060,
  radius: 1000 // meters
};

// Invalid coordinates for testing
const invalidCoordinates = {
  outOfRange: { latitude: 999, longitude: 999 },
  missing: { latitude: null, longitude: null },
  strings: { latitude: 'abc', longitude: 'xyz' }
};

// Error messages
const errorMessages = {
  invalidCredentials: 'Invalid credentials.',
  usernameInUse: 'Username already in use.',
  missingFields: 'Missing required fields.',
  unauthorized: 'Unauthorized',
  forbidden: 'Forbidden',
  notFound: 'not found',
  serverError: 'Server error'
};

module.exports = {
  validUserCredentials,
  validBusinessCredentials,
  validAdminCredentials,
  sampleStores,
  sampleBusinesses,
  sampleRoutes,
  sampleAchievements,
  nearbySearchParams,
  invalidCoordinates,
  errorMessages
};
