// View routes script - displays all routes in the database
require('dotenv').config();
const sequelize = require('../config/database');
const Route = require('../models/routes');

async function viewRoutes() {
    try {
        console.log('Connecting to database...');
        await sequelize.authenticate();
        console.log('Database connection established.\n');

        console.log('Fetching all routes...');
        const routes = await Route.findAll({
            order: [['id', 'ASC']]
        });

        if (routes.length === 0) {
            console.log('No routes found in the database.');
        } else {
            console.log(`\nFound ${routes.length} route(s):\n`);

            // Format routes for display
            const formattedRoutes = routes.map(route => ({
                ID: route.id,
                Name: route.name,
                Type: route.routeType,
                'Auto-Generated': route.isAutoGenerated ? 'Yes' : 'No',
                Created: route.createdAt ? new Date(route.createdAt).toLocaleString() : 'N/A'
            }));

            console.table(formattedRoutes);
        }

        process.exit(0);
    } catch (error) {
        console.error('Error fetching routes:', error);
        process.exit(1);
    }
}

viewRoutes();
